# Generated by Django 5.1.5 on 2025-01-20 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('INDIA', 'IND'), ('PAKISTAN', 'PAK'), ('AUSTRALIA', 'AUS'), ('SRI LANKA', 'SL')], max_length=20)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=50)),
                ('umpire', models.CharField(max_length=50)),
                ('inning', models.IntegerField(choices=[(1, 1), (2, 2), (0, 0)])),
                ('status', models.CharField(max_length=50)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='api.teams')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='api.teams')),
                ('toss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teams')),
            ],
        ),
    ]
