# Generated by Django 5.1.5 on 2025-01-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teams_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchTitle',
            field=models.CharField(default='Match Title ', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='team1FallenWickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1OverPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2FallenWickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2OverPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='inning',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)]),
        ),
    ]
