# Generated by Django 5.1.5 on 2025-01-22 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_player_matchplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ballsBowled',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ballsPlayed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fours',
        ),
        migrations.RemoveField(
            model_name='player',
            name='isBowling',
        ),
        migrations.RemoveField(
            model_name='player',
            name='isOut',
        ),
        migrations.RemoveField(
            model_name='player',
            name='maidenBowled',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matchPlayed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='runScored',
        ),
        migrations.RemoveField(
            model_name='player',
            name='runsGiven',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sixes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wicketsTaken',
        ),
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runScored', models.IntegerField()),
                ('ballsPlayed', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('ballsBowled', models.IntegerField()),
                ('runsGiven', models.IntegerField()),
                ('maidenBowled', models.IntegerField()),
                ('wicketsTaken', models.IntegerField()),
                ('isOut', models.CharField(choices=[('out', 'out'), ('notOut', 'notOut'), ('onStrike', 'onStrike'), ('nonStrike', 'nonStrike')], max_length=50)),
                ('isBowling', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('matchPlayed', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='matchesPlayed', to='api.match')),
            ],
        ),
    ]
