# Generated by Django 5.1.5 on 2025-01-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_player_ballsbowled_remove_player_ballsplayed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team1OverPlayed',
            new_name='team1BallsPlayed',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2OverPlayed',
            new_name='team2BallsPlayed',
        ),
    ]
