# Generated by Django 5.1.5 on 2025-01-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_playerperformance_name_teams_isbatting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
