# Generated by Django 5.1.5 on 2025-01-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_playerperformance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerperformance',
            name='matchPlayed',
        ),
    ]
