# Generated by Django 5.1.5 on 2025-01-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='isBatting',
        ),
    ]
