# Generated by Django 5.1.5 on 2025-01-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_player_name_playerperformance_matchplayed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerperformance',
            name='matchPlayed',
        ),
    ]
