# Generated by Django 5.1.5 on 2025-01-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_teams_isbatting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='isBatting',
        ),
        migrations.AddField(
            model_name='match',
            name='batting',
            field=models.CharField(choices=[('INDIA', 'IND'), ('PAKISTAN', 'PAK'), ('AUSTRALIA', 'AUS'), ('SRI LANKA', 'SL')], max_length=50, null=True),
        ),
    ]
