# Generated by Django 5.1.5 on 2025-01-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='news/')),
            ],
        ),
    ]
