# Generated by Django 5.1.5 on 2025-01-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matchPlayed',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='matchesPlayed', to='api.match'),
        ),
    ]
