# Generated by Django 5.1.5 on 2025-01-23 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_team1overplayed_match_team1ballsplayed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playersname', to='api.player'),
        ),
        migrations.AddField(
            model_name='teams',
            name='isBatting',
            field=models.BooleanField(default=False),
        ),
    ]
