# Generated by Django 5.1.5 on 2025-01-23 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerperformance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playersname', to='api.player'),
        ),
    ]
