# Generated by Django 5.1.5 on 2025-01-23 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_teams_isbatting'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='isBatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameOfPlayer', to='api.player'),
        ),
    ]
