# Generated by Django 5.1.5 on 2025-01-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_teams_isbatting_alter_playerperformance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerperformance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='isBatting',
        ),
    ]
