# Generated by Django 5.1.5 on 2025-01-23 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_playerperformance_name_remove_teams_isbatting'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nameOfPlayer', to='api.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='isBatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='matchPlayed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchesPlayed', to='api.match'),
        ),
    ]
