# Generated by Django 5.1.5 on 2025-01-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_playerperformance_name_teams_isbatting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerperformance',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nameOfPlayer', to='api.player'),
        ),
    ]
