# Generated by Django 5.1.5 on 2025-01-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_playerperformance_matchplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
