# Generated by Django 5.1.5 on 2025-01-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_teams_isbatting'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='name',
            field=models.CharField(default='PlayerName', max_length=50),
        ),
    ]
