# Generated by Django 5.1.5 on 2025-01-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_playerperformance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='matchPlayed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matchesPlayed', to='api.match'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nameOfPlayer', to='api.player'),
        ),
    ]
