# Generated by Django 5.1.5 on 2025-01-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_playerperformance_matchplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='matchPlayed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matchesPlayed', to='api.match'),
        ),
    ]
