# Generated by Django 5.1.5 on 2025-01-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='isBatting',
            field=models.BooleanField(default=False),
        ),
    ]
