# Generated by Django 5.1.5 on 2025-01-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_match_batting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerperformance',
            name='ballsBowled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='ballsPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='isOut',
            field=models.CharField(choices=[('notOut', 'notOut'), ('out', 'out'), ('onStrike', 'onStrike'), ('nonStrike', 'nonStrike')], max_length=50),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='maidenBowled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='runScored',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='runsGiven',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='wicketsTaken',
            field=models.IntegerField(default=0),
        ),
    ]
