# Generated by Django 5.1.5 on 2025-01-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_playerperformance_ballsbowled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerperformance',
            name='wicketsTaken',
            field=models.IntegerField(default=1),
        ),
    ]
