# Generated by Django 5.1.5 on 2025-01-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_playerperformance_wicketstaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerperformance',
            name='wicketsTaken',
            field=models.IntegerField(default=0),
        ),
    ]
