# Generated by Django 5.1.5 on 2025-01-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_playerperformance_wicketstaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='favPosition',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=1),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='positionPlayed',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=1),
        ),
    ]
