# Generated by Django 5.1.5 on 2025-01-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_player_favposition_playerperformance_positionplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
