# Generated by Django 5.1.5 on 2025-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_player_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live',
            field=models.CharField(max_length=50, null=True, verbose_name=[('toBeStarted', 'toBeStarted'), ('live', 'live'), ('result', 'result')]),
        ),
    ]
