# Generated by Django 5.1.5 on 2025-01-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_match_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='live',
            field=models.CharField(choices=[('toBeStarted', 'toBeStarted'), ('live', 'live'), ('result', 'result')], max_length=50, null=True),
        ),
    ]
