# Generated by Django 5.1.5 on 2025-01-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_commentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='inning',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2)]),
        ),
    ]
