# Generated by Django 5.1.5 on 2025-01-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_match_inning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentry',
            name='runs',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (6, 6)], default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='inning',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)]),
        ),
    ]
