# Generated by Django 5.1.5 on 2025-01-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_commentry_runs_alter_match_inning'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentry',
            name='batter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batter', to='api.player'),
        ),
        migrations.AddField(
            model_name='commentry',
            name='bowler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowler', to='api.player'),
        ),
    ]
