# Generated by Django 5.1.5 on 2025-01-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_commentry_batter_commentry_bowler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team',
            field=models.CharField(choices=[('INDIA', 'IND'), ('PAKISTAN', 'PAK'), ('AUSTRALIA', 'AUS'), ('SRI LANKA', 'SL'), ('MI', 'MI'), ('CSK', 'CSK'), ('RCB', 'RCB')], max_length=20),
        ),
    ]
