# Generated by Django 5.1.5 on 2025-01-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_teams_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentry',
            name='defaultCommentry',
            field=models.CharField(choices=[('four', "That's a great shot. FOUR"), ('four', 'This is a HUUUGE SIX '), ('bowled', "He didn't have clue How ball got swing in. Bowled "), ('dot', 'Nice Delivey from the Bowler '), ('spin', ' That is a top spin from bowler '), ('googly', ' This is Googly ')], max_length=100, null=True),
        ),
    ]
