# Generated by Django 5.1.5 on 2025-01-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_commentry_defaultcommentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentry',
            name='commentryText',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
